### PR TITLE
WIP: Add SPM support

### PR DESCRIPTION
**Pull request by mchoo7**
https://github.com/davbeck/TUSafariActivity/issues/33

If we want to replace Cocoapods in the Example project, we should change the name of the project since the dependency name and the project name cannot be the same. [See here](https://stackoverflow.com/questions/71003426/xcode-13-2-1-multiple-commands-produce-issue)

 - [x] Create `Package.swift`
 - [x] Migrate the example project to use SPM instead of CocoaPods
 - [x] Fix `podspec` to reflect changes

### CODE REVIEW

**Review by davbeck — APPROVED** [review]

**Comment by davbeck** [comment]
Happy to merge if once the conflicts are resolved.

**Comment by fel1x-developer** [comment]
I still need to fix codes and I am working on it.

**Comment by fel1x-developer** [comment]
Merge conflict is now resolved.

**Comment by farajwm-sudo** [comment]
swiftpackage

**Comment by farajwm-sudo** [comment]
> swiftpackage

**Comment by farajwm-sudo** [comment]
> > swiftpackage
> 
>

**Pull request merged**
